CREATE TABLE IF NOT EXISTS admins (id INTEGER PRIMARY KEY AUTOINCREMENT, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, email TEXT, role TEXT DEFAULT 'admin', login_attempts INTEGER DEFAULT 0, locked_until DATETIME, last_login DATETIME, reset_token TEXT, reset_token_expires DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_admins_username ON admins(username); 
CREATE INDEX IF NOT EXISTS idx_admins_email ON admins(email); 
CREATE INDEX IF NOT EXISTS idx_admins_reset_token ON admins(reset_token); 
CREATE TABLE IF NOT EXISTS sessions (id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT UNIQUE NOT NULL, user_id INTEGER NOT NULL, expires_at DATETIME NOT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (user_id) REFERENCES admins(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_sessions_session_id ON sessions(session_id); 
CREATE INDEX IF NOT EXISTS idx_sessions_expires_at ON sessions(expires_at); 
CREATE INDEX IF NOT EXISTS idx_sessions_user_id ON sessions(user_id); 
CREATE TABLE IF NOT EXISTS subscribers (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT UNIQUE NOT NULL, first_name TEXT DEFAULT '', last_name TEXT DEFAULT '', status TEXT NOT NULL DEFAULT 'pending', verification_token TEXT UNIQUE, unsubscribe_token TEXT UNIQUE, categories TEXT DEFAULT 'general', source TEXT DEFAULT 'website', ip_address TEXT, user_agent TEXT, referrer TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, verified_at DATETIME, unsubscribed_at DATETIME, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_subscribers_email ON subscribers(email); 
CREATE INDEX IF NOT EXISTS idx_subscribers_status ON subscribers(status); 
CREATE INDEX IF NOT EXISTS idx_subscribers_verification_token ON subscribers(verification_token); 
CREATE INDEX IF NOT EXISTS idx_subscribers_unsubscribe_token ON subscribers(unsubscribe_token); 
CREATE INDEX IF NOT EXISTS idx_subscribers_created_at ON subscribers(created_at DESC); 
CREATE INDEX IF NOT EXISTS idx_subscribers_status_created ON subscribers(status, created_at DESC); 
CREATE TABLE IF NOT EXISTS newsletter_preferences (id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER NOT NULL, category TEXT NOT NULL, subscribed INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE, UNIQUE(subscriber_id, category)); 
CREATE INDEX IF NOT EXISTS idx_preferences_subscriber ON newsletter_preferences(subscriber_id); 
CREATE INDEX IF NOT EXISTS idx_preferences_category ON newsletter_preferences(category); 
CREATE INDEX IF NOT EXISTS idx_preferences_subscribed ON newsletter_preferences(subscriber_id, subscribed); 
CREATE TABLE IF NOT EXISTS newsletter_campaigns (id INTEGER PRIMARY KEY AUTOINCREMENT, subject TEXT NOT NULL, content_html TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'draft', category TEXT DEFAULT 'general', scheduled_at DATETIME, sent_at DATETIME, total_recipients INTEGER DEFAULT 0, opened_count INTEGER DEFAULT 0, clicked_count INTEGER DEFAULT 0, bounced_count INTEGER DEFAULT 0, unsubscribed_count INTEGER DEFAULT 0, created_by INTEGER, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (created_by) REFERENCES admins(id) ON DELETE SET NULL); 
CREATE INDEX IF NOT EXISTS idx_campaigns_status ON newsletter_campaigns(status); 
CREATE INDEX IF NOT EXISTS idx_campaigns_scheduled_at ON newsletter_campaigns(scheduled_at); 
CREATE INDEX IF NOT EXISTS idx_campaigns_sent_at ON newsletter_campaigns(sent_at); 
CREATE INDEX IF NOT EXISTS idx_campaigns_created_at ON newsletter_campaigns(created_at DESC); 
CREATE INDEX IF NOT EXISTS idx_campaigns_status_scheduled ON newsletter_campaigns(status, scheduled_at); 
CREATE TABLE IF NOT EXISTS newsletter_deliveries (id INTEGER PRIMARY KEY AUTOINCREMENT, campaign_id INTEGER NOT NULL, subscriber_id INTEGER NOT NULL, status TEXT DEFAULT 'queued', sent_at DATETIME, opened_at DATETIME, clicked_at DATETIME, error_message TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (campaign_id) REFERENCES newsletter_campaigns(id) ON DELETE CASCADE, FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_deliveries_campaign ON newsletter_deliveries(campaign_id); 
CREATE INDEX IF NOT EXISTS idx_deliveries_subscriber ON newsletter_deliveries(subscriber_id); 
CREATE INDEX IF NOT EXISTS idx_deliveries_status ON newsletter_deliveries(status); 
CREATE INDEX IF NOT EXISTS idx_deliveries_campaign_status ON newsletter_deliveries(campaign_id, status); 
CREATE INDEX IF NOT EXISTS idx_deliveries_created_at ON newsletter_deliveries(created_at DESC); 
CREATE TABLE IF NOT EXISTS unsubscribe_feedback (id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER NOT NULL, reason TEXT, feedback TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_unsubscribe_feedback_subscriber ON unsubscribe_feedback(subscriber_id); 
CREATE INDEX IF NOT EXISTS idx_unsubscribe_feedback_created ON unsubscribe_feedback(created_at DESC); 
CREATE TABLE IF NOT EXISTS posts (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, content TEXT NOT NULL, excerpt TEXT, category TEXT DEFAULT 'Uncategorized', tags TEXT DEFAULT '', cover_image TEXT DEFAULT '', is_draft INTEGER DEFAULT 1, is_published INTEGER DEFAULT 0, views INTEGER DEFAULT 0, author_id INTEGER, published_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, is_todays_pick INTEGER DEFAULT 0, is_recently_added INTEGER DEFAULT 0, FOREIGN KEY (author_id) REFERENCES admins(id) ON DELETE SET NULL); 
CREATE INDEX IF NOT EXISTS idx_posts_slug ON posts(slug); 
CREATE INDEX IF NOT EXISTS idx_posts_is_published ON posts(is_published); 
CREATE INDEX IF NOT EXISTS idx_posts_created_at ON posts(created_at DESC); 
CREATE INDEX IF NOT EXISTS idx_posts_author_id ON posts(author_id); 
CREATE INDEX IF NOT EXISTS idx_posts_category ON posts(category); 
CREATE INDEX IF NOT EXISTS idx_posts_is_todays_pick ON posts(is_todays_pick); 
CREATE INDEX IF NOT EXISTS idx_posts_is_recently_added ON posts(is_recently_added); 
CREATE INDEX IF NOT EXISTS idx_posts_published_at ON posts(published_at DESC); 
CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_categories_slug ON categories(slug); 
CREATE INDEX IF NOT EXISTS idx_categories_name ON categories(name); 
CREATE TABLE IF NOT EXISTS media (id INTEGER PRIMARY KEY AUTOINCREMENT, filename TEXT NOT NULL, original_name TEXT NOT NULL, url TEXT NOT NULL, file_size INTEGER, mime_type TEXT, alt_text TEXT DEFAULT '', folder TEXT DEFAULT '', uploaded_by TEXT DEFAULT 'admin', uploader_id INTEGER, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (uploader_id) REFERENCES admins(id) ON DELETE SET NULL); 
CREATE INDEX IF NOT EXISTS idx_media_filename ON media(filename); 
CREATE INDEX IF NOT EXISTS idx_media_created_at ON media(created_at DESC); 
CREATE INDEX IF NOT EXISTS idx_media_mime_type ON media(mime_type); 
CREATE INDEX IF NOT EXISTS idx_media_folder ON media(folder); 
CREATE INDEX IF NOT EXISTS idx_media_uploader_id ON media(uploader_id); 
CREATE TABLE IF NOT EXISTS products (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, category TEXT, brand TEXT, cover_image TEXT DEFAULT '', in_stock INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, is_top_pick INTEGER DEFAULT 0, is_newly_released INTEGER DEFAULT 0); 
CREATE INDEX IF NOT EXISTS idx_products_slug ON products(slug); 
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category); 
CREATE INDEX IF NOT EXISTS idx_products_is_top_pick ON products(is_top_pick); 
CREATE INDEX IF NOT EXISTS idx_products_is_newly_released ON products(is_newly_released); 
CREATE TABLE IF NOT EXISTS product_resources (id INTEGER PRIMARY KEY AUTOINCREMENT, product_id INTEGER NOT NULL, platform TEXT NOT NULL CHECK (platform IN ('reddit', 'youtube', 'tiktok', 'shop')), url TEXT NOT NULL, title TEXT NOT NULL, description TEXT, thumbnail_url TEXT, author TEXT, shop_name TEXT, published_at DATETIME, is_featured INTEGER DEFAULT 0, display_order INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_resources_product_id ON product_resources(product_id); 
CREATE INDEX IF NOT EXISTS idx_resources_platform ON product_resources(platform); 
CREATE INDEX IF NOT EXISTS idx_resources_product_platform ON product_resources(product_id, platform); 
CREATE INDEX IF NOT EXISTS idx_resources_featured ON product_resources(is_featured); 
CREATE INDEX IF NOT EXISTS idx_resources_active ON product_resources(is_active); 
CREATE TABLE IF NOT EXISTS templates (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, category TEXT NOT NULL, content TEXT NOT NULL, description TEXT DEFAULT '', thumbnail_url TEXT DEFAULT '', is_active INTEGER DEFAULT 1, usage_count INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, created_by INTEGER); 
CREATE INDEX IF NOT EXISTS idx_templates_category ON templates(category); 
CREATE INDEX IF NOT EXISTS idx_templates_name ON templates(name); 
CREATE INDEX IF NOT EXISTS idx_templates_category_name ON templates(category, name); 
CREATE INDEX IF NOT EXISTS idx_templates_is_active ON templates(is_active); 
CREATE TABLE IF NOT EXISTS reliable_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, icon TEXT DEFAULT '??', display_order INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_reliable_categories_slug ON reliable_categories(slug); 
CREATE INDEX IF NOT EXISTS idx_reliable_categories_active ON reliable_categories(is_active); 
CREATE TABLE IF NOT EXISTS reliable_subcategories (id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, display_order INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES reliable_categories(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_reliable_subcategories_category ON reliable_subcategories(category_id); 
CREATE INDEX IF NOT EXISTS idx_reliable_subcategories_slug ON reliable_subcategories(slug); 
CREATE INDEX IF NOT EXISTS idx_reliable_subcategories_active ON reliable_subcategories(is_active); 
CREATE TABLE IF NOT EXISTS reliable_sub_subcategories (id INTEGER PRIMARY KEY AUTOINCREMENT, subcategory_id INTEGER NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, display_order INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (subcategory_id) REFERENCES reliable_subcategories(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_sub_subcategories_subcategory ON reliable_sub_subcategories(subcategory_id); 
CREATE INDEX IF NOT EXISTS idx_sub_subcategories_slug ON reliable_sub_subcategories(slug); 
CREATE INDEX IF NOT EXISTS idx_sub_subcategories_active ON reliable_sub_subcategories(is_active); 
CREATE TABLE IF NOT EXISTS reliable_websites (id INTEGER PRIMARY KEY AUTOINCREMENT, subcategory_id INTEGER NOT NULL, sub_subcategory_id INTEGER, name TEXT NOT NULL, url TEXT NOT NULL, description TEXT, reliability_score INTEGER DEFAULT 5, notes TEXT, country TEXT DEFAULT 'USA', language TEXT DEFAULT 'English', logo_url TEXT, is_featured INTEGER DEFAULT 0, is_active INTEGER DEFAULT 1, last_verified DATE, verified_by TEXT, usage_count INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (subcategory_id) REFERENCES reliable_subcategories(id) ON DELETE CASCADE, FOREIGN KEY (sub_subcategory_id) REFERENCES reliable_sub_subcategories(id) ON DELETE SET NULL, UNIQUE(url, subcategory_id, sub_subcategory_id)); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_subcategory ON reliable_websites(subcategory_id); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_sub_subcategory ON reliable_websites(sub_subcategory_id); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_score ON reliable_websites(reliability_score DESC); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_name ON reliable_websites(name); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_active ON reliable_websites(is_active); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_featured ON reliable_websites(is_featured); 
CREATE INDEX IF NOT EXISTS idx_reliable_websites_url ON reliable_websites(url); 
CREATE TABLE IF NOT EXISTS reliable_verification_log (id INTEGER PRIMARY KEY AUTOINCREMENT, website_id INTEGER NOT NULL, verified_by TEXT, verification_date DATE, old_score INTEGER, new_score INTEGER, status TEXT DEFAULT 'verified', notes TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (website_id) REFERENCES reliable_websites(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_verification_website ON reliable_verification_log(website_id); 
CREATE INDEX IF NOT EXISTS idx_verification_date ON reliable_verification_log(verification_date); 
CREATE TABLE IF NOT EXISTS content_types (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, icon TEXT DEFAULT '??', color TEXT DEFAULT '#3b82f6', description TEXT, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_content_types_slug ON content_types(slug); 
CREATE TABLE IF NOT EXISTS content_categories (id INTEGER PRIMARY KEY AUTOINCREMENT, category_id INTEGER NOT NULL, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, description TEXT, is_active INTEGER DEFAULT 1, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (category_id) REFERENCES reliable_categories(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_content_categories_category ON content_categories(category_id); 
CREATE INDEX IF NOT EXISTS idx_content_categories_slug ON content_categories(slug); 
CREATE TABLE IF NOT EXISTS content_status (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, color TEXT DEFAULT '#94a3b8', display_order INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP); 
CREATE INDEX IF NOT EXISTS idx_content_status_slug ON content_status(slug); 
INSERT OR IGNORE INTO content_status (name, slug, color, display_order) VALUES ('Idea', 'idea', '#94a3b8', 1), ('Draft', 'draft', '#f59e0b', 2), ('In Review', 'in-review', '#8b5cf6', 3), ('Scheduled', 'scheduled', '#3b82f6', 4), ('Published', 'published', '#22c55e', 5); 
CREATE TABLE IF NOT EXISTS content (id INTEGER PRIMARY KEY AUTOINCREMENT, title TEXT NOT NULL, slug TEXT UNIQUE NOT NULL, content TEXT, excerpt TEXT, content_type_id INTEGER NOT NULL, category_id INTEGER, status_id INTEGER DEFAULT 1, author_id INTEGER, featured_image TEXT, cover_image TEXT, tags TEXT DEFAULT '', meta_title TEXT, meta_description TEXT, meta_keywords TEXT, scheduled_publish_at DATETIME, published_at DATETIME, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP, is_published INTEGER DEFAULT 0, is_featured INTEGER DEFAULT 0, views INTEGER DEFAULT 0, source_url TEXT, source_name TEXT, source_type TEXT DEFAULT 'original', FOREIGN KEY (content_type_id) REFERENCES content_types(id) ON DELETE CASCADE, FOREIGN KEY (category_id) REFERENCES content_categories(id) ON DELETE SET NULL, FOREIGN KEY (status_id) REFERENCES content_status(id) ON DELETE SET NULL, FOREIGN KEY (author_id) REFERENCES admins(id) ON DELETE SET NULL); 
CREATE INDEX IF NOT EXISTS idx_content_slug ON content(slug); 
CREATE INDEX IF NOT EXISTS idx_content_status ON content(status_id); 
CREATE INDEX IF NOT EXISTS idx_content_scheduled_publish_at ON content(scheduled_publish_at); 
CREATE INDEX IF NOT EXISTS idx_content_published_at ON content(published_at); 
CREATE INDEX IF NOT EXISTS idx_content_category ON content(category_id); 
CREATE INDEX IF NOT EXISTS idx_content_type ON content(content_type_id); 
CREATE INDEX IF NOT EXISTS idx_content_is_published ON content(is_published); 
CREATE TABLE IF NOT EXISTS content_resources (id INTEGER PRIMARY KEY AUTOINCREMENT, content_id INTEGER NOT NULL, reliable_website_id INTEGER, url TEXT NOT NULL, title TEXT, description TEXT, type TEXT DEFAULT 'link', display_order INTEGER DEFAULT 0, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (content_id) REFERENCES content(id) ON DELETE CASCADE, FOREIGN KEY (reliable_website_id) REFERENCES reliable_websites(id) ON DELETE SET NULL); 
CREATE INDEX IF NOT EXISTS idx_content_resources_content ON content_resources(content_id); 
CREATE TABLE IF NOT EXISTS content_history (id INTEGER PRIMARY KEY AUTOINCREMENT, content_id INTEGER NOT NULL, user_id INTEGER, action TEXT NOT NULL, field TEXT, old_value TEXT, new_value TEXT, note TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (content_id) REFERENCES content(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_content_history_content ON content_history(content_id); 
CREATE TABLE IF NOT EXISTS newsletter_activity (id INTEGER PRIMARY KEY AUTOINCREMENT, subscriber_id INTEGER NOT NULL, campaign_id INTEGER NOT NULL, action TEXT NOT NULL, url TEXT, ip_address TEXT, user_agent TEXT, created_at DATETIME DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (subscriber_id) REFERENCES subscribers(id) ON DELETE CASCADE, FOREIGN KEY (campaign_id) REFERENCES newsletter_campaigns(id) ON DELETE CASCADE); 
CREATE INDEX IF NOT EXISTS idx_activity_subscriber ON newsletter_activity(subscriber_id); 
CREATE INDEX IF NOT EXISTS idx_activity_campaign ON newsletter_activity(campaign_id); 
CREATE INDEX IF NOT EXISTS idx_activity_action ON newsletter_activity(action); 
CREATE INDEX IF NOT EXISTS idx_activity_created_at ON newsletter_activity(created_at DESC); 
