name = "trendlin-newsletter-worker"
main = "src/workers/send-newsletter.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "trendlin-db"
database_id = "4c7e58ee-38af-49ed-ab76-62a07050a2f9"

[vars]
SITE = "https://trendlin.com"

[triggers]
crons = ["*/5 * * * *"]  # Every 5 minutes